name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-hack
      - uses: extractions/setup-just@v2
      - uses: taiki-e/install-action@protoc
      - name: Test
        run: just test
      - name: Lint
        run: just lint
